### ISSUE TITLE
[Biometric] Demo Application Crash BiometricDemoD11

### ISSUE THREAD

**Issue by sfoms** [DelphiWorlds/Kastri#88] opened 2022-01-13 13:45 UTC
When you press the fingerprint scanner icon, the application crashes and gives the following error:

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/biometric/R$string;
	at androidx.biometric.BiometricFragment.authenticate(BiometricFragment.java:381)
	at androidx.biometric.BiometricPrompt.authenticateInternal(BiometricPrompt.java:993)
	at androidx.biometric.BiometricPrompt.authenticate(BiometricPrompt.java:972)
	at com.delphiworlds.kastri.DWBiometricFragmentActivity.authenticate(DWBiometricFragmentActivity.java:91)
	at com.delphiworlds.kastri.DWBiometricFragmentActivity.onResume(DWBiometricFragmentActivity.java:106)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
	at android.app.Activity.performResume(Activity.java:7400)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3890)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6820)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.biometric.R$string" on path: DexPathList[[zip file "/data/app/com.delphiworlds.BiometricDemoD11-alBMpzbi0kV5Eu8m3O07dg==/base.apk"],nativeLibraryDirectories=[/data/app/com.delphiworlds.BiometricDemoD11-alBMpzbi0kV5Eu8m3O07dg==/lib/arm, /data/app/com.delphiworlds.BiometricDemoD11-alBMpzbi0kV5Eu8m3O07dg==/base.apk!/lib/armeabi-v7a, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 19 more

Delphi Version: 11
Platform(s): Android 9 PPR1.160610.011
Device: Redmi 6, MIUI Global 11.0.5

**Comment by DelphiWorlds** [comment] 2022-01-13 20:18
I'm unable to reproduce this issue on my Pixel 6 Pro (Android 12) or Pixel 3a (Android 11). I don't have an Android 9 device with biometrics to check why it happens on yours

**Comment by sfoms** [comment] 2022-01-13 20:29
When you run this function, this problem occurs:

function TPlatformBiometric.ShowPrompt: Boolean;
begin
  Result := False;
  if GetBiometricCapability = TBiometricCapabilityResult.Available then
  begin
    TJDWBiometricFragmentActivity.JavaClass.start(TAndroidHelper.Context, GetPromptInfoIntent);
    Result := True;
  end;
end;


And to be even more precise:

TJDWBiometricFragmentActivity.JavaClass.start(TAndroidHelper.Context, GetPromptInfoIntent);



P.S. Sorry for my English.  It's not my native language...

**Comment by DelphiWorlds** [comment] 2022-01-14 00:19
I have updated the demo with a change that may fix it. You will need to update your Kastri library to obtain all the required changes

**Comment by sfoms** [comment] 2022-01-14 02:37
I will be waiting very much.  Thank you very much.

**Comment by sfoms** [comment] 2022-01-14 03:56
After the update, the error is still the same, only different:
java.lang.RuntimeException: Unable to resume activity {com.delphiworlds.BiometricDemoD11/com.delphiworlds.kastri.DWBiometricFragmentActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3858)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3890)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:150)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6820)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)

Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
at android.content.res.Resources.getText(Resources.java:360)
at android.content.res.MiuiResources.getText(MiuiResources.java:97)
at android.content.res.Resources.getString(Resources.java:453)
at androidx.fragment.app.Fragment.getString(Fragment.java:986)
at androidx.biometric.BiometricFragment.authenticate(BiometricFragment.java:382)
at androidx.biometric.BiometricPrompt.authenticateInternal(BiometricPrompt.java:993)
at androidx.biometric.BiometricPrompt.authenticate(BiometricPrompt.java:972)
at com.delphiworlds.kastri.DWBiometricFragmentActivity.authenticate(DWBiometricFragmentActivity.java:91)
at com.delphiworlds.kastri.DWBiometricFragmentActivity.onResume(DWBiometricFragmentActivity.java:106)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
at android.app.Activity.performResume(Activity.java:7400)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
... 11 more

**Comment by DelphiWorlds** [comment] 2022-01-14 08:43
Sorry.. I know where the problem is. I just need to work out how to fix it :-)

**Comment by DelphiWorlds** [comment] 2022-01-15 06:02
I've pushed an update to the biometric R jar (androidx-biometric-1.1.0.R.jar). Can you pull the change, do a Clean of your project and try again?

**Comment by sfoms** [comment] 2022-01-15 06:24
Unfortunately, I can't compile. Here's an error:

[PAClient Error] Error: E7432 Error in C:\Users\Public\Documents\Embarcadero\_Comp\Kastri\ThirdParty\Android\androidx-biometric-1.1.0.R.jar:
[PAClient Error] Error: E7432 java.util.zip.ZipException: error in opening zip file

**Comment by DelphiWorlds** [comment] 2022-01-15 06:43
Not sure why it would not be compiling for you - compiles OK here

**Comment by sfoms** [comment] 2022-01-15 06:48
I have updated OpenJDK to version 8.0.3.312.7 but the error remains.

Maybe you updated some more files, but did not post them? :)

**Comment by DelphiWorlds** [comment] 2022-01-15 06:49
That's the only file that was changed

**Comment by sfoms** [comment] 2022-01-15 06:52
I don't know why, but I rebooted the computer and the project compiled. Now I'll try to run it on different devices. Thanks!

**Comment by sfoms** [comment] 2022-01-15 07:08
Опять ошибка:

java.lang.RuntimeException: Unable to resume activity {com.delphiworlds.BiometricDemoD11/com.delphiworlds.kastri.DWBiometricFragmentActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f070000
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3858)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3890)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:150)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6820)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f070000
at android.content.res.Resources.getText(Resources.java:360)
at android.content.res.MiuiResources.getText(MiuiResources.java:97)
at android.content.res.Resources.getString(Resources.java:453)
at androidx.fragment.app.Fragment.getString(Fragment.java:986)
at androidx.biometric.BiometricFragment.authenticate(BiometricFragment.java:382)
at androidx.biometric.BiometricPrompt.authenticateInternal(BiometricPrompt.java:993)
at androidx.biometric.BiometricPrompt.authenticate(BiometricPrompt.java:972)
at com.delphiworlds.kastri.DWBiometricFragmentActivity.authenticate(DWBiometricFragmentActivity.java:91)
at com.delphiworlds.kastri.DWBiometricFragmentActivity.onResume(DWBiometricFragmentActivity.java:106)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
at android.app.Activity.performResume(Activity.java:7400)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
... 11 more


On the Honor 9 phone, it also crashes (but I can’t see the error on it).

**Comment by DelphiWorlds** [comment] 2022-01-15 07:27
Can you attach the .APK file, please

**Comment by sfoms** [comment] 2022-01-15 07:32
[BiometricDemoD11.zip](https://github.com/DelphiWorlds/Kastri/files/7874483/BiometricDemoD11.zip)

**Comment by DelphiWorlds** [comment] 2022-01-15 07:42
I may have missed a change to the project file. Please pull the latest changes, and rebuild your project

**Comment by sfoms** [comment] 2022-01-15 07:59
Absolutely the same error... :(

**Comment by DelphiWorlds** [comment] 2022-01-15 08:02
Can you post a screenshot of your Deployment window? i.e. in Delphi, use Project|Deployment. It should look like this:

![image](https://user-images.githubusercontent.com/22670829/149614501-39be2d01-4ab7-4e8b-9351-b6b051591ccb.png)

Note all the files that have been added

**Comment by DelphiWorlds** [comment] 2022-01-15 08:04
Here is my APK so you can check if it works on your device
[BiometricDemoD11.apk.zip](https://github.com/DelphiWorlds/Kastri/files/7874530/BiometricDemoD11.apk.zip)
.

**Comment by sfoms** [comment] 2022-01-15 08:06
![Snap2](https://user-images.githubusercontent.com/97411388/149614615-97e48017-2787-41d6-abc3-d05eba09e99a.PNG)
![Snap3](https://user-images.githubusercontent.com/97411388/149614617-62f13a19-ac31-4237-bba4-9067d51ae83c.PNG)
![Snap1](https://user-images.githubusercontent.com/97411388/149614618-ccd88935-6b10-454c-b8f5-dd5b65650a3c.PNG)

**Comment by sfoms** [comment] 2022-01-15 08:08
Your APK also causes the application to the same error... (

**Comment by DelphiWorlds** [comment] 2022-01-15 08:11
Without the same (or similar) device to test on, I do not think I can help at the moment

**Comment by sfoms** [comment] 2022-01-15 08:16
Is it possible to make it so that when an error occurs, the application does not crash?

Something like:
try
except

**Comment by DelphiWorlds** [comment] 2022-01-15 08:18
Unfortunately, no - the crash actually occurs in the Java code for biometrics.

**Comment by sfoms** [comment] 2022-01-15 08:35
What do we do? :)

**Comment by DelphiWorlds** [comment] 2022-01-16 19:09
[BiometricDemoD11.apk.zip](https://github.com/DelphiWorlds/Kastri/files/7877714/BiometricDemoD11.apk.zip)

Can you try the attached APK?

**Comment by sfoms** [comment] 2022-01-17 04:01
Good afternoon.
The error remains the same.
I tried to change the localization of the phone (I thought it might have something to do with it), but nothing has changed...

**Comment by DelphiWorlds** [comment] 2022-01-17 04:13
OK.. I may have a solution another way, hopefully

**Comment by sfoms** [comment] 2022-01-17 04:15
Fine! I will be very hopeful!

**Comment by DelphiWorlds** [comment] 2022-01-17 12:37
I have just pushed a change to `androidx-biometric-1.1.0-R.jar`. Can you pull the change, do a Clean on your project, rebuild and try it, please? This should at least have the demo working. I am looking into implementing a solution that can apply to any project

**Comment by sfoms** [comment] 2022-01-17 13:05
Everything is fine!
Thanks a lot!!!

P.S. And the localization of the word "Authenticate!" possible in a popup window?

**Comment by sfoms** [comment] 2022-01-17 13:39
Solved the issue with the title!
Thank you very much!

**Comment by sfoms** [comment] 2022-01-27 15:59
Hello!
There is a new problem: 
On Honor X8 phone, with "Secure File Sharing" enabled, the app crashes when the fingerprint is read or canceled.

As soon as you disable "Secure File Sharing" everything works.

**Comment by DelphiWorlds** [comment] 2022-01-27 21:25
In future, please report new issues separately, however: can you check that your AndroidManifest.template.xml file has:

```
<%provider%>
```

in it?

**Comment by sfoms** [comment] 2022-01-28 02:39
Yes, of course, <%provider%> is contained in the AndroidManifest.template.xml file

**Comment by DelphiWorlds** [comment] 2022-03-28 00:27
Long time issue still unresolved - requires changes to the build process.

**Comment by Mouscap** [comment] 2022-06-10 06:02
Hello,
I was previously using the KeyguardManager to authenticate the user. But as it's now deprecated, I have tried to use your BiometricDemoD11 App. I have the same issue than the one explained at the start of this discussion : When I press the fingerprint icon, the application crashes but the only error I get is "BiometricDemoD11 stopped working"... I don't know how to get more details...
When I try to execute in debug mode, the `TPlatformBiometric.ShowPrompt` seems to work Ok as well as the `TJDWBiometricFragmentActivity.JavaClass.start(TAndroidHelper.Context, GetPromptInfoIntent)` call but the process crashes after the return.
My target is Android 8.1.0 : I have read that AndroidX is supported by this platform.
Thank you for your help

Delphi Version: 11.1
Target = Android 8.1.0 - Nexus 6P

**Comment by DelphiWorlds** [comment] 2022-06-12 23:49
Thanks for the reminder.. I've set another reminder for myself for during this week

**Comment by Mouscap** [comment] 2022-06-13 05:43
Thank you very much

**Comment by DelphiWorlds** [comment] 2022-06-20 09:44
Perhaps tomorrow, if not, the next day :-)

**Comment by DelphiWorlds** [comment] 2022-06-29 21:45
I would like to be able to provide a solution for this that is easy to incorporate, however it is very complicated. If the Delphi build system was more flexible, it would be easier.

The issue is this: As you have discovered, on some devices (I do not know why it is only some), the biometrics expects there to be certain values in the application resources, however in the case of Delphi, they are not compiled in with the application. This Quality Portal report has some background about that:

https://quality.embarcadero.com/browse/RSP-20000

In Delphi, currently the build steps for Android are (essentially) like this:

Compile/Build steps:
1. Compile/link application code
2. Merge "dex" files

Deploy steps:
1. Generate resource files
2. Deploy compiled files and resources
3. Package the app

In order for the biometrics resources to be included in the application, the steps would need to be like this:

Compile/Build steps:
1. Compile/link application code
2. Generate resource files
3. Merge resources from other Android libraries (such as biometrics) with those generated by Delphi
4. Compile "R" classes for the included libraries into a jar, and "dex" it
5. Merge "dex" files

Deploy steps:
1. Deploy compiled files and resources
2. Package the app

It is **possible** to achieve the same result, however it involves these steps:

1. Do a deployment **once**
2. Merge resources from other Android libraries (such as biometrics) with those generated by Delphi
3. Compile "R" classes for the included libraries into a jar, and "dex" it
4. Add the "dexed" file to the libraries for the project
5. In deployment manager, uncheck all the files that would normally be deployed to the "res" folder, and add the "merged" files generated in step 2. It is not an easy task to do this with Deployment Manager in its current state, however the [DeployMan tool](https://github.com/grijjy/GrijjyDeployMan) from Grijjy could help here.
6. Do a deployment again

Usually, these steps will need to be done only once, however if **any** changes are made to the project that result in different resource files, steps 1-3 will definitely need to be repeated, and some changes related to step 5 may also need to be considered.

I am working on tools that can automate steps 2-3, however I'd much prefer it if Embarcadero could resolve the Quality Portal issue mentioned above

**Comment by DelphiWorlds** [comment] 2022-09-15 08:31
@Mouscap (and anyone else following) - I have pushed a ["beta" demo to the Playground repo](https://github.com/DelphiWorlds/Playground/tree/main/Demos/Biometric), which you are welcome to try, and give feedback on. Please report any such feedback or issues to the [Playground issues page](https://github.com/DelphiWorlds/Playground/issues).

**Comment by edsonalanis** [comment] 2022-12-02 10:26
> @Mouscap (and anyone else following) - I have pushed a ["beta" demo to the Playground repo](https://github.com/DelphiWorlds/Playground/tree/main/Demos/Biometric), which you are welcome to try, and give feedback on. Please report any such feedback or issues to the [Playground issues page](https://github.com/DelphiWorlds/Playground/issues).

These steps only work for 32-bit Android, how to do the same for 64-bit which is the version we posted on Google Play?

**Closed** 2023-02-04 00:14 UTC
Labels: bug
